# Generated by Django 3.2.16 on 2022-11-26 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='avaiablity',
            new_name='availability',
        ),
    ]
