# Generated by Django 3.2.16 on 2022-11-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_avaiablity_inventory_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
